"""create initial ledger schema

Revision ID: a2f258febe71
Revises: 
Create Date: 2026-08-28 16:02:57.694009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2f258febe71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_value_cents', sa.Integer(), nullable=True),
    sa.Column('value_as_of', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate_to_eur', sa.Float(), nullable=True),
    sa.Column('shipping_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('fees_cents', sa.Integer(), nullable=False),
    sa.Column('order_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_in_id', sa.Integer(), nullable=True),
    sa.Column('acquired_amount_cents', sa.Integer(), nullable=True),
    sa.Column('disposed_in_id', sa.Integer(), nullable=True),
    sa.Column('disposed_amount_cents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquired_in_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['disposed_in_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copy')
    op.drop_table('transaction')
    op.drop_table('product')
    op.drop_table('counterparty')
    # ### end Alembic commands ###
